### ISSUE TITLE
Overlay Link Broken - Routes to a DNS site

### ISSUE THREAD

**Issue by GravByte** [opl-/beatsaber-stream-overlay#1]
This overlay no longer works.
The link brings me to this website: http://www.freenom.link/en/index.html?lang=en

**Comment by opl-** [comment]
I'm aware and already made an attempt at resolving this situation, but unfortunately it's like talking to a brick wall.

For the time being, you can do this instead:
- [download this ZIP](https://github.com/opl-/beatsaber-stream-overlay/files/7288733/beatsaber-stream-overlay-7ff5f06f.zip),
- unpack it on your computer.
- open the `index.html` file in a browser,
- use the configuration page as normal, clicking "open overlay" to confirm the settings,
- copy the `file://` URI from the address bar into OBS.

Alternatively, you can take a look at the [other overlays](https://github.com/opl-/beatsaber-http-status/wiki/Software-using-this-plugin).

**Comment by GravByte** [comment]
> I'm aware and already made an attempt at resolving this situation, but unfortunately it's like talking to a brick wall.
> 
> For the time being, you can do this instead:
> 
> * [download this ZIP](https://github.com/opl-/beatsaber-stream-overlay/files/7288733/beatsaber-stream-overlay-7ff5f06f.zip),
> * unpack it on your computer.
> * open the `index.html` file in a browser,
> * use the configuration page as normal, clicking "open overlay" to confirm the settings,
> * copy the `file://` URI from the address bar into OBS.
> 
> Alternatively, you can take a look at the [other overlays](https://github.com/opl-/beatsaber-http-status/wiki/Software-using-this-plugin).

Ok thank you very much!

**Comment by opl-** [comment]
The domain should work as usual now.
